/*
 * CONFIGURACIÓN PÚBLICA DEL CLIENTE.
 * No coloque secretos aquí: GitHub Pages publica este archivo.
 */
window.APP_CONFIG = Object.freeze({
  API_URL: "https://script.google.com/macros/s/AKfycbzhuqur9BMvbZsdUcnhAVOSjVfASzZ8T8dqcDj60HsMtFOrul2OzFfSS_DRqIOXjkWg/exec",
  SURVEY_ID: "DEMO-001",
  TURNSTILE_SITE_KEY: "0x4AAAAAAD5SxL30_U0FV8FL",
  TURNSTILE_ACTION: "survey_access",
  API_TIMEOUT_MS: 30000,
  POLL_INTERVAL_MS: 700,
  AUDIO_CHUNK_MS: 20000,
  AUDIO_BITS_PER_SECOND: 64000,
  MAX_SESSION_HOURS: 3,
  MIN_REQUIRED_STORAGE_MB: 300,
  REQUIRE_PERSISTENT_STORAGE: false,
  MIN_AUDIO_RMS: 0.012,
  AUDIO_TEST_MS: 3500,
  HEARTBEAT_MS: 45000,
  PBKDF2_ITERATIONS: 600000,
  MIN_PASSPHRASE_LENGTH: 12,
  SERVICE_WORKER_ENABLED: true
});
